datalad/datalad-registry

- datalad_registry/tests/conftest.py
Despite the tests passing at the moment, celery's database reference
can leak across the tests (see the example in gh-2).  For upcoming
tests that I'm working on, this mismatch causes failures.
I bet there's a proper way to set up a function-scoped fixture that
calls create_app() and doesn't have this problem, but after a good
amount of flailing, I haven't found it.
So, instead move the create_app() call, which brings along the setup
of the database and celery, into a session-scoped fixture.  Convert
app_instance(), the main fixture used by the tests, into a
function-scoped fixture that sits on top of the session-scoped
fixture, refreshing the tables before a test runs.
Closes #2.
> tests: Share database connection across tests

- datalad_registry/datasets.py
- datalad_registry/factory.py
- datalad_registry/tests/conftest.py
- datalad_registry/tests/test_dataset_urls.py
- datalad_registry/tests/test_datasets.py
- datalad_registry/tests/utils.py
- docs/openapi.yml
Closes #5.
---
For the most part I've just tested this via pytest.
> views: Add endpoint for listing dataset IDs

- README.md
- datalad_registry/dataset_urls.py
- datalad_registry/datasets.py
- datalad_registry/models.py
- datalad_registry/tasks.py
- datalad_registry/tests/conftest.py
- datalad_registry/tests/test_dataset_urls.py
- datalad_registry/tests/test_datasets.py
- datalad_registry/tests/test_tasks.py
- datalad_registry/tests/utils.py
- docs/openapi.yml
The separation should make it more obvious that this is referring to
the dataset ID.
Suggested by @yarikoptic in gh-11.
---
Or should we just go with a full `dataset_id`?
> Use 'ds_id' rather than 'dsid'

- datalad_registry/factory.py
- datalad_registry/models.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
> tasks: Collect annex.uuid of source repository

- datalad_registry/factory.py
- datalad_registry/overview.py
- datalad_registry/root.py
- datalad_registry/static/main.css
- datalad_registry/templates/overview.html
- datalad_registry/tests/test_datasets.py
- datalad_registry/tests/test_overview.py
- datalad_registry/tests/test_root.py
- datalad_registry/tests/test_tasks.py
- datalad_registry/tests/utils.py
This series adds a view that presents the registered datasets in a table and at least partially addresses gh-6.
> Add web view with a simple overview table

- datalad_registry/models.py
- datalad_registry/overview.py
- datalad_registry/tasks.py
- datalad_registry/templates/overview.html
> Add git_objects_kb field

- datalad_registry/dataset_urls.py
- datalad_registry/datasets.py
- datalad_registry/models.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_datasets.py
- tox.ini
> Endpoint for URL without ID

- datalad_registry/datasets.py
- datalad_registry/tasks.py
- datalad_registry_client/__init__.py
- datalad_registry_client/consts.py
- datalad_registry_client/opts.py
- datalad_registry_client/submit.py
- datalad_registry_client/submit_urls.py
- datalad_registry_client/tests/test_submit.py
- datalad_registry_client/tests/test_submit_urls.py
> Add registry-submit-urls command

- datalad_registry_client/opts.py
- datalad_registry_client/submit.py
- datalad_registry_client/tests/test_submit.py
> Support invoking `registry-submit` with neither `--sibling` nor `--url`

- .dockerignore
- .github/workflows/test.yml
- Dockerfile
- datalad_registry/__init__.py
- pyproject.toml
- setup.cfg
- tox.ini
> Use versioningit

- datalad_registry/models.py
> Use an integer as the primary key

- datalad_registry/dataset_urls.py
- datalad_registry/datasets.py
- datalad_registry/models.py
- datalad_registry/tasks.py
> Better handle submitting the same URL to multiple endpoints at once

- datalad_registry/models.py
- datalad_registry/tasks.py
Store size of annexed files in working tree as an integer
> Store size of annexed files as int

- requirements.txt
- requirements_dev.txt
- setup.cfg
Provide a more precise dependency specification by modifying the `setup.cfg` file and adding requirement files.
> Provide more precise dependency specification

- Dockerfile
- datalad_registry/config.py
- datalad_registry/dataset_urls.py
- datalad_registry/factory.py
- datalad_registry/runcelery.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
Closes #38 and annotated the code with numerous todos.
> Process multiple datasets in parallel

- datalad_registry/dataset_urls.py
- datalad_registry/datasets.py
- datalad_registry/overview.py
- datalad_registry/root.py
Remove unneeded checks of HTTP methods inside view functions, and make acceptable HTTP methods more explicit.
> HTTP Method handling

- datalad_registry/templates/overview.html
- datalad_registry/tests/test_overview.py
Display URLs in the web UI as hyperlinks. This PR resolves https://github.com/datalad/datalad-registry/issues/111.
> Web UI: Display URLs as hyperlinks

- datalad_registry/templates/overview.html
Put in a consistent format with regard to indention so that the IDE won't give me surprises when I edit different parts of this file.
> Reformat overview.html with consistent indents

- datalad_registry/factory.py
- datalad_registry/models.py
- migrations/README
- migrations/alembic.ini
- migrations/env.py
- migrations/script.py.mako
- requirements.txt
- setup.cfg
Set up the project to do database migration using [Flask-Migrate](https://flask-migrate.readthedocs.io/en/latest/).
This PR is intended to resolve https://github.com/datalad/datalad-registry/issues/124.
> Feature: DB migrate

- datalad_registry/blueprints/api/url_metadata.py
Improved comments and created a URL prefix for dataset URL metadata routes.
> Refactor: Refactor codes related to API endpoints for dataset URL metadata

- datalad_registry/templates/overview.html
This PR updates a name reference in overview.html to complete the changes needed to close #177.
> Update `url_metadata` endpoint name in overview.html

- datalad_registry_client/submit_urls.py
- datalad_registry_client/tests/test_submit_urls.py
This PR polishes the implementation of the `registry-submit-urls` command and its related tests
> Refine `registry-submit-urls` command 

- requirements_dev.txt
- setup.cfg
Add mypy and types-requests to dev dependency for we use these packages in GitHub workflow already
> Add mypy and types-requests to dev dependency

- .github/workflows/test.yml
- datalad_registry/config.py
- datalad_registry/models.py
- datalad_registry/tests/conftest.py
- datalad_registry/tests/test_tasks/test_process_dataset_url.py
- requirements.txt
- setup.cfg
This PR upgrade SQLAlchemy to 2.0.
This PR closes #88.
Changes of this PR has been applied to the running instance of Datalad-registry on Typhon.
> Update: Update the project to support SQLAlchemy 2.0

- datalad_registry/tests/test_utils/test_datalad_tls.py
- datalad_registry/utils/datalad_tls.py
> Add authordate to branch record

- dev.dockerfile
- docker-compose.dev.yml
This PR improves the Docker environment used for development in the following aspects:
1. Defining a new docker file, `dev.dockerfile`,  that doesn't copy app code to the docker image to improve build time.
2. Bind mounting the app code to containers (specified in `docker-compose.dev.yml`)
3. Exposing all the ports of the services to the local host for easy access (specified in `docker-compose.dev.yml`)
> Improve Docker environment for development

- requirements.txt
This PR updates the DataLad dependency to the latest version, 0.19.3.
> Update datalad to the latest version, 0.19.3

- README.md
- datalad_registry/overview.py
- template.env.testing
It also includes fixes to sample invocations on how to "source" properly
If doesn't break -- let's merge, unless you see easy ways to extend existing test to also add basic testing for searching metadata
> Add stupid simple search/filter based on searching metadata

- datalad_registry/overview.py
This PR is a follow up to #241 and #242. It allows the search/filter of dataset URLs to be done in a case-insensitive manner.
> Feature: Implement case-insensitive search using `ilike()`

- requirements.txt
This resolve the issue that #261 intended to resolve.
> Update datalad_neuroimaging dependency to 0.3.4

- README.md
- datalad_registry/__init__.py
- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/utils.py
- datalad_registry/tests/test__init__.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
- datalad_registry/utils/flask_tools.py
- docker-compose.dev.yml
- docker-compose.read-only.local.override.yml
- docker-compose.read-only.yml
- template.env.read-only
This PR is intended to fulfill #195.
This PR is based on #238. To get the relevant commit for this PR, merge the master branch into the associated branch after #238 is merged into the master branch.
> Read-only instance

- dev.Dockerfile
Base Docker image of project on phusion/baseimage. It has the correct init process that ensures all orphaned child processes are reaped.
> Base Docker image of project on phusion/baseimage

- dev.Dockerfile
The change in this PR creates and utilizes a Python virtual environment in containers running the services in Datalad-Registry. Before change in this PR, these services were run in the system's Python environment which contains some packages unrelated to Datalad-Registry. 
The change in this PR provides an additional level of isolation, and allows the Python environment used in the container to be identical to the one used in development.
> Create and utilize Python virtual environment in containers

- datalad_registry/overview.py
- datalad_registry/search.py
- datalad_registry/templates/overview.html
- datalad_registry/tests/test_search.py
This PR brings in the following minor improvements to #308:
1. Improvement in the last example for the query syntax
2. Replace a use of list with use of a generator for performance.
3. Update to the modern SQLAlchemy syntax in `overview.py` and `test_search.py`.
> Various minor improvements

- datalad_registry/static/main.css
- datalad_registry/templates/overview.html
This PR contains few miscellaneous improvements/corrections to the HTML template and the CSS file. For details of the individual improvements, please check out respective commit for details.
> Miscellaneous improvements to HTML template and CSS

- requirements.dev.txt
- requirements.test.txt
- requirements.txt
This formatting is more consistent with the format in setup.cfg and more readable
> Put a space before and after `==` in requirement files

- datalad_registry_client/get_urls.py
- datalad_registry_client/submit_urls.py
- datalad_registry_client/utils.py
This PR refactors some of the code in the `datalad_registry_client` package. The details of the refactoring is available through the commit message of individual commits.
> RF: Refactor client

- datalad_registry/templates/overview.html
This PR humanizes the count and file size values in the main table.
Notes: It is based on #353. To get the relevant commits of this PR, merge master to this PR after #353 is merged to master.
> Humanize count and file size values in the main table
