datalad/datalad-registry

- datalad_registry/dataset_urls.py
- datalad_registry/models.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_dataset_urls.py
- datalad_registry/tests/test_tasks.py
- docs/openapi.yml
This gives `datalad publish/push` a way to announce an update to the
registry.  The underlying task is still very basic in terms of how it
decides to collect information on the URLs and what information it
collects.
---
An example of wiring this up to `datalad push` is at <https://github.com/datalad/datalad/compare/master...kyleam:registry>.
> Provide endpoint for announcing a dataset update

- datalad_registry/dataset_urls.py
- datalad_registry/datasets.py
- datalad_registry/tests/test_tasks.py
- docs/openapi.yml
Extend the response for `GET /v1/datasets/{ds_id}/urls/{url_encoded}` with "info" field that includes some of the collected information.
Partially addresses gh-9.
> views: Extend URL endpoint with some collected information

- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
- datalad_registry/tests/utils.py
collect_dataset_info() clones the URL with `git clone --mirror ...`.
That's convenient and easy but won't work once we start collecting
more information via DataLad.
Do a fairly minimal switch to using DataLad and a non-bare repo.  If
later desired/needed, some of the call_git() sites can be switched
over to GitRepo methods.
As indicated by the tests, the only change in collected information is
the inclusion of the remote HEAD symref in the list of branches.
That's not a useful addition, but it's also probably not worth
worrying about or filtering out at this point.
> tasks: Switch to DataLad for collecting information

- datalad_registry/dataset_urls.py
- datalad_registry/models.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
- docs/openapi.yml
- setup.cfg
Add "annex_key_count" to the info reported by `GET /datasets/{ds_id}/urls/{url_encoded}`.
Closes #10.
> tasks: Collect number of annex keys at source repository

- .coveragerc
- .github/workflows/test.yml
- conftest.py
- datalad_registry/dataset_urls.py
- datalad_registry/factory.py
- datalad_registry_client/__init__.py
- datalad_registry_client/announce_update.py
- datalad_registry_client/opts.py
- datalad_registry_client/submit.py
- datalad_registry_client/tests/test_announce_update.py
- datalad_registry_client/tests/test_submit.py
- pyproject.toml
- setup.cfg
- setup.py
- up
- up-tests
~This is a draft (at the very least needs tests)~ This series is work towards gh-8.  At the moment it has functional subcommands for registering a new URL and for announcing an update, which I think is a good stopping point.
The beginning of the series is mostly concerned with reworking the `up` script so that it can be used reliably in the context of automated tests.  (Before this point, the `app_instance` and `client` fixtures were sufficient.)
> Add client as DataLad extension

- datalad_registry/dataset_urls.py
- datalad_registry/factory.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
* Increase the frequency of checking for updates.
* Add an intermediate directory level to the layout of cloned datasets to better handle a large number of datasets.
* Launch the background task for cloning and information collection when a dataset is registered (rather than relying on a periodic task).
> Tweaks to information collection

- tox.ini
About the ignored warning: datalad imports annexremote, which imports future, which imports imp, which is deprecated in favor of importlib.  I can't find future's repository or bug tracker (as the "Fork me on GitHub" link in its docs doesn't work), so I don't know if or when they're going to address this warning.  However, the latest (unreleased) code in annexremote's repository drops the dependency on future, so by the time the next version of annexremote gets released, the warning will go away.
> Make pytest error on warnings, ignoring deprecation warning from future

- datalad_registry_client/__init__.py
ATM it is not installed as an independent python module, so would just
reuse datalad-registry I guess for the version.  With this
datalad wtf -S extensions
would provide proper version
> Provide __version__ for datalad_registry_client

- .github/dependabot.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.
> Update GitHub Actions action versions

- datalad_registry/tasks.py
The return of call_annex_records() is already a list. There is no need to convert the return into another list again.
> Remove unneeded list construction

- datalad_registry/models.py
- datalad_registry/overview.py
- datalad_registry/tasks.py
- datalad_registry/templates/overview.html
Count and size of annexed files in working tree are now extracted and included in web UI.
> Extend metadata extracted from git-annex

- datalad_registry/tasks.py
- tox.ini
By ensuring the existence of the containing directory of the destination of any cloned dataset, a clone dataset can now be store in the cache directory.
> Fix:  Solved the problem of cloned datasets not being stored in cache

- datalad_registry/tasks.py
- setup.cfg
Utilize @validate_arguments from Pydantic to ensure arguments of Celery tasks are received in their intended types, not corrupted by the transmission in JSON.
This PR fixes the problem of sending a celery task with an argument of a tuple, but the responding celery worker receiving an argument of a list.
>  Ensure Celery tasks receive arguments in correct type

- setup.cfg
The latest SQLAlchemy, version 2.0, 01-26-2023, is currently incompatible with our project. Let's restrict the version of SQLAlchemy to before 2.0 for now.
> Restrict SQLAlchemy to version before 2.0

- .github/workflows/lint.yml
- .github/workflows/test.yml
- setup.cfg
As discussed with Yarik, the minimum supported Python version of the project is set to 3.9. This PR simply update the setup configurations and GitHub action workflows to implement this agreed change.
> Update the minimum support Python version

- .github/workflows/lint.yml
- setup.cfg
Upgrading to incompatible version should be done manually.
> Prevent Black from upgrading to incompatible version automatically

- datalad_registry/factory.py
Since our Flask app is defined in a module in a package, `__name__` shouldn't be used as the first param in initiating it. For more info, see https://flask.palletsprojects.com/en/2.2.x/api/#application-object.
> Define the name of the Flask app correctly

- docker-compose.yml
This PR changes few specs for the Celery broker:
1. Set a password
2. For security, restrict access to localhost only
3. Expose only the relevant environment variables
> Modify broker container specifications

- datalad_registry/tasks.py
- datalad_registry/tests/test_tasks.py
Cloning a dataset sometimes can fail with an IncompleteResultsError. Simply retrying will resolve the problem in most cases.
This PR is only a step toward a solution for https://github.com/datalad/datalad-registry/issues/93. A complete solution would require the handling of the case in which all retries of cloning fail. However, with this PR, the population of datasets would be stable enough for the work for https://github.com/datalad/datalad-registry/issues/89 to start.
> BF: Handle IncompleteResultsError in cloning dataset

- requirements.txt
- setup.cfg
psycopg2-binary is not meant to be used as a dependency of a published package. For details, please see
https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary. Using psycopg2-binary actually caused a failure in communication with Postgres in the container built based on the Debian image.
> Replace psycopg2-binary with psycopg2 as a dependency

- docker-compose.dev.yml
Use bind mounts instead of named volumes for easy of allocation of resources in the host machine.
> Use bind mounts instead of named volumes

- tools/populate.py
Ensure the URLs submitted by each run of the `population.py` script are unique. This is useful in getting the actual number of datasets to be handled by the datalad registry instance.
> Unique urls

- tools/populate.py
While [dictionaries are insertion ordered](https://stackoverflow.com/a/39980744/4635580), sets are not. It is better to use a dictionary to preserve the order of dataset URLs read from the usage dashboard so that we get the URLs for submission to the Datalad registry instance in a consistent order across multiple runs of the `population.py` script.
> Use dict to preserve order of retrieved URLs for population

- requirements_dev.txt
- setup.cfg
The project already uses isort and flake8 in pre-commit and GitHub workflows. This PR specifies them as dev requirements in `setup.cfg` and `requirements_dev.txt`
> Specify isort and flake8 as dev dependencies

- datalad_registry/models.py
- migrations/versions/769fc6a4d2ea_removing_customized___tablename___urls_.py
[`__tablename__` doesn't need to be defined when using Flask-SQLAlchemy's model](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/models/#defining-models). Let's remove the customized table name and adopt the naming convention implemented by Flask-SQLAlchemy.
> Remove customized table name

- setup.cfg
Relax Flask-Migrate version restriction so that all sub-versions of version 4 are allowed.
> Relax Flask-Migrate version restriction

- datalad_registry/tests/conftest.py
Replace the use of `yield` with `return` in pytest fixtures when there is nothing to be clean up afterward. The use of `yield` in `app_instance` is also problematic because it puts all tests using `app_instance` in the created app's app context implicitly and unnecessarily. For more detailed info, please checkout out https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/contexts/#tests.
> Replace the use of `yield` in pytest fixtures

- datalad_registry/factory.py
- datalad_registry/tests/test_new_organization/test_api_json_error_response.py
This PR is intended to resolve https://github.com/datalad/datalad-registry/issues/121.
This PR is built upon https://github.com/datalad/datalad-registry/pull/113. It should be rebased after https://github.com/datalad/datalad-registry/pull/113 is merged to master to get the relevant commit.
> Make sure error responses from /api/ are in JSON format

- datalad_registry/overview.py
This PR is intended to resolve https://github.com/datalad/datalad-registry/issues/132.
With the changes in this PR, all items with NULL values are allocated to the end of the result of a sort, regardless of the order of the sort, descending or ascending.
These changes have been made available in the running instance of Datalad-registry on Typhon
> Sort with NULL values at the end of the result

- datalad_registry/tests/test_new_organization/conftest.py
This PR is based on https://github.com/datalad/datalad-registry/pull/138. It should be rebased after https://github.com/datalad/datalad-registry/pull/138 is merged to get the relevant commits of this PR.
> Enable testing mode for the Datalad-registry Flask app in tests

- datalad_registry/tasks.py
Redefine `.git/objects` size as the sum of "size" and "size-pack" of `count_objects` of the dataset repo.
This PR is intended to resolve #135.
P.S. This new definition of `.git/objects` size has been applied to the running instance of Datalad-registry on Typhon.
> Redefine .git/objects size

- datalad_registry/overview.py
- datalad_registry/static/main.css
- datalad_registry/templates/overview.html
- datalad_registry/tests/test_overview.py
This PR brings a reimplementation of the pagination mechanism in the web UI. It resolves #143 and provides a more direct implementation the pagination mechanism by removing quite a few unnecessary variables.
P.S. Changes in this PR has been applied to the running instance of Datalad-registry on Typhon.
> Reimplement pagination

- datalad_registry/blueprints/api/__init__.py
- datalad_registry/blueprints/api/url_metadata.py
- datalad_registry/com_models.py
- datalad_registry/factory.py
- datalad_registry/tests/test_new_organization/test_api_json_error_response.py
- datalad_registry/tests/test_new_organization/test_blueprints/test_api/test_url_metadata.py
- datalad_registry/tests/test_new_organization/test_tasks/test_extract_meta.py
- requirements.txt
- setup.cfg
This PR adds [Flask OpenAPI3](https://luolingchun.github.io/flask-openapi3/), a extension of Flask, as a dependency. Leveraging Flask OpenAPI3, all parsing and validation of incoming data from the API can be specified and handled by Pydantic. Additionally, an up-to-date OpenAPI specification of the API is aways available with interactive documentation such as Swagger.
As a proof concept, this PR has only made the endpoint related to URL metadata available in the OpenAPI specification. More API endpoints will be made available very soon in subsequent PRs.
The changes in the PR has been applied to the Datalad Registry instance on Typhon. Please visit `/openapi` for the interactive documentation of the API.
> Feature: Utilize Flask OpenAPI3 in parsing, validation in APIs and generation of OpenAPI specs

- .github/workflows/test.yml
codecov is [no longer available on pypi](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader). It's present in the Python environment of GitHub Actions workflow is not really needed because the uploading of coverage to codecov has been taken care of by `codecov/codecov-action@v3`.
> Remove `codecov` in Python environ of GitHub Actions workflow

- .github/workflows/test.yml
- datalad_registry/blueprints/api/__init__.py
- datalad_registry/blueprints/api/dataset_urls.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_new_organization/test_blueprints/test_api/test_dataset_urls.py
- datalad_registry/utils/flask_tools.py
This PR provides RESTful API endpoints for accessing dataset URLs. The up-to-date documentation of these endpoints is available in the OpenAPI standard and available for view at `/openapi` of the Datalad-registry on Typhon.
Please note that [the backend of the `POST /api/v2/dataset-urls` endpoint](https://github.com/datalad/datalad-registry/blob/5ec5915c6de4cff3016c7c037a5c465e4c1674de/datalad_registry/tasks.py#L450) is not yet implemented but will be provided in a subsequent PR.
The PR is based on #152 and should be rebased once #152 is merged.
> REST API endpoints for dataset URls

- datalad_registry/blueprints/api/dataset_urls.py
- datalad_registry/tasks.py
- datalad_registry/tests/test_new_organization/test_tasks/__init__.py
- datalad_registry/tests/test_new_organization/test_tasks/conftest.py
- datalad_registry/tests/test_new_organization/test_tasks/test_extract_ds_meta.py
- datalad_registry/tests/test_new_organization/test_tasks/test_process_dataset_url.py
Modify the Datalad-registry client to adopt API V2 of Datalad-registry.
This PR closes https://github.com/datalad/datalad-registry/issues/164
> Modify Datalad-registry client to adopt to API V2

- datalad_registry/tasks.py
Enable retrying for the processing of dataset URLs should it encounters `datalad.support.exceptions.IncompleteResultsError`.  `datalad.support.exceptions.IncompleteResultsError` can arise in the process cloning of a dataset. It can possibly arise in the gathering of basic information about a dataset URL as well. In any case, the processing of dataset URLs, `process_dataset_url`, is idempotent and can safely retried.
This PR closes https://github.com/datalad/datalad-registry/issues/169.
> Enable retrying for processing dataset URLs

- datalad_registry/tasks.py
This PR marks idempotent Celery tasks to acknowledge after each task has been executed, not to acknowledge immediately before the task starts executing (the default behavior). Doing so increases the reliability of idempotent Celery tasks by ensuring their execution after the crash of a Celery worker and help the developer identify which Celery tasks are idempotent.
More information can be found at https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.acks_late and https://docs.celeryq.dev/en/stable/faq.html#faq-acks-late-vs-retry.
This PR depends on #170.
> Mark idempotent tasks to acknowledge late

- datalad_registry/factory.py
- docker-compose.dev.yml
The old cron job of `collect_dataset_info` never worked, and it is not compatible with the new local cache organization. This PR removes the scheduling of `collect_dataset_info` and disable the scheduler service. The scheduler will be re-enabled once there is a job to be scheduled. For now, disabling it allows easier debugging of other services.
> Disable Celery scheduler

- datalad_registry/config.py
- datalad_registry/tasks.py
- requirements.txt
- setup.cfg
- tools/populate_url_metadata.py
Add extraction of BIDS metadata, as defined by the `bids_dataset` extractor  in `datalad_neuroimaging`  of registered URLs that meet the requirements of such extraction. This PR closes #141.
Additionally, this PR also updates the tool script of `populate_url_metadata.py` to populate the running instance of datalad-reistry on Typhon with the BIDS metadata.
> Feature: Add BIDS metadata extraction support

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/blueprints/api/url_metadata/__init__.py
- datalad_registry/blueprints/api/url_metadata/models.py
The PR extract models in `dataset_urls` and `url_metadata` and put them in separate files. This eliminates circular imports caused by using these models by external code that also defines the `datalad.api` dynamically.
This PR closes #177.
> Resolve additional potential circular imports

- datalad_registry_client/tests/test_submit_urls.py
This PR provides a test for verifying the `registry_submit_urls` command is indeed registered with the Datalad API
> Add test for registering of `registry_submit_urls`

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/blueprints/api/url_metadata/models.py
- datalad_registry/tests/test_new_organization/test_blueprints/test_api/test_dataset_urls.py
- datalad_registry_client/tests/test_get_urls.py
This PR closes #176.
This PR adds the query parameter of `return_metadata` to the `GET /api/v2/dataset-urls` endpoint. If this query parameter is not provided, the `metadata` field of each returned dataset URL object will be `null`. If this query parameter is "reference", the `metadata` field of each returned dataset URL object will be a list of objects each presenting a reference link to a piece of metadata of the dataset at the URL. If this query parameter is "content", the `metadata` field of each returned dataset URL object will be a list of objects each presenting a piece of metadata of the dataset at the URL.
Note: I used "reference" instead of "references" as a value of `return_metadata` because I feel that this value is an adjective pertaining to how each piece of metadata should …
> Feature: Make metadata available through the dataset URLs API endpoint

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tests/test_new_organization/test_blueprints/test_api/test_dataset_urls.py
This PR renames `OrderKey.git_objects_size` to `OrderKey.git_objects_kb` per @yarikoptic's [suggestion](`OrderKey.git_objects_size` to `OrderKey.git_objects_kb`).
> Rename `OrderKey.git_objects_size` to `OrderKey.git_objects_kb`

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tests/test_new_organization/test_blueprints/test_api/test_dataset_urls.py
- datalad_registry_client/tests/test_get_urls.py
This PR modifies the API so that no field having the value of `null` will be returned as part of an API response. A field that has the value of `null` in an API response before this PR will not be contained in the comparable API response after this PR.
This PR resolves the issue brought up in https://github.com/datalad/datalad-registry/pull/184#discussion_r1221783199.
Changes in this PR have been applied to the running instance of datalad-registry on Typhon
> Improvement: Skip `null` fields in API responses

- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tasks.py
- datalad_registry/utils/misc.py
- tools/populate.py
This PR closes #189.
This is PR is based on #190, so merge master into this PR's branch after #190 is merged into master to get the relevant commits of this PR.
Changes in this PR have been applied to the running instance of datalad-registry on Typhon
> override `_generate_next_value_` in `StrEnum` and use it in the subclasses of `StrEnum` by calling `auto()`

- datalad_registry/tests/test_utils/test_datalad_tls.py
This PR removes the bug in this test that causes intermittent failures mostly due to the failure to get log of the referenced branch instead of the log of `HEAD`. Additionally, it makes this test independent of the order of the branches returned by git.
> Debug `test_get_origin_branches()`

- docker-compose.dev.yml
This PR redefines the broker service by enabling the management plugin in RabbitMQ, redefining its health check, and persisting its data through a bind mount.
This PR closes #174.
> Redefine the broker (RabbitMQ) service)

- docker-compose.dev.yml
- requirements.txt
- setup.cfg
This PR adds [Flower](https://flower.readthedocs.io/en/latest/) as a service to monitor the Celery cluster. The service is a web app available at port 5555.
The Flower service is set up to run in persistent mode and information about workers and tasks will be saved to the disk periodically.
The changes of this PR will be applied to the running instance of Datalad-registry at Typhon together with the solution for #112. Once that application happens, we should consider closing #133 for the changes in the PR should satisfy the goal of #133.
> Feature: Add Celery monitoring service

- requirements.txt
- setup.cfg
Pydantic 2.0 is out, and it may not be compatible with our code
> Upgrade pydantic to 1.10.11 and pin it to below 2.0

- docker-compose.dev.yml
BASH, the intended shell, may not be the default shell in some of the images we are using. This PR ensures all the health check tests are executed in BASH, the intended shell, or directly, without a shell.
This will eliminate some possible unexpected behaviors. For example, the default shell for Debian is DASH. We can get some unexpected behaviors if we assume the executing shell to be BASH but the actually executing shell is DASH.
> Execute health check test in bash or directly

- docker-compose.dev.yml
This PR sets the monitor service, Flower, to use relative time to display tasks info. With this setting, timestamps will be shown as relative time, relative to the page refresh time, such as “2 minutes ago” or “1 hour ago”. This setting will allow user to easily identify recently executed tasks.
Additionally, this PR also remove the setting of the `FLOWER_ENABLE_EVENTS` environment variable for it is not necessary since the default for this setting is our intended value.
> Set monitor service to use relative time

- .dockerignore
This PR further improves the build speed of the Docker image by excluding tests to be copied to the image.
> Exclude tests to be copied to the docker image

- .dockerignore
This will possibly help Docker CLI speed up the determination of the content of the context.
> Minor: Tell docker to ignore `__pycache__` directories before telling it to ignore the `.pyc` files

- docker-compose.dev.yml
Podman currently doesn't support health check tests in list form. This PR expresses all health check tests in shell script form. Additionally, this PR add the following feature to health checks.
1. Specifies start period and start interval for health checks
2. Un-silence all health checks so that their output can be captured and logged.
> Adjust Healthcheck for Podman and other improvements

- docker-compose.dev.yml
It is not yet supported in docker compose
> Remove `start_interval` in `healthcheck`

- datalad_registry/conf.py
- datalad_registry/tests/test__init__.py
- datalad_registry/tests/test_conf.py
Place limits on the repeated use of individual worker processes. If a worker process has been used more than 1000 times or has used more than 500MB resident memory, it will be replaced by a new worker process. These configurations are put in place to control affect of possible memory leaks.
For more information, please check out the following documentations.
1. https://docs.celeryq.dev/en/stable/userguide/workers.html#max-tasks-per-child-setting
2. https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-worker_max_tasks_per_child
> Place limits on the repeated use of individual worker processes

- requirements.txt
This PR updates Celery and Flower to the latest versions, 5.3.1 and 2.0.1, respectively.
> Update Celery and Flower dependency

- datalad_registry/__init__.py
- datalad_registry/tests/test_utils/test_pydantic_json.py
- datalad_registry/utils/pydantic_json.py
This PR adds support for additional types as Celery task arguments.
This PR allows arguments of Celery tasks to be of any type that is allowed as a field type of a Pydantic model. Thus, an argument of a Celery task can be the type of `datetime.datetime`, `decimal.Decimal`, `pathlib.Path`, `uuid.UUID`, Pydantic models themselves, and more.
> Additional type support for Celery task arguments

- datalad_registry/overview.py
This PR is a follow up to PR #241.
Some minor improvements are added to the filtering/searching of dataset URLs as follow
1. Cast `extracted_metadata` to `Text`
-  `Text` type documents the content is of variable length
2. `Text` and enable `autoescape`
-   Enabling `autoescape` ensures the value to search for is interpreted as a string literal
> Minor improvements to search/filter of dataset URLs

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
This PR enables the web API to handle simultaneous submissions of the same dataset URL
> Handle simultaneous submissions of the same dataset URL

- datalad_registry/__init__.py
This PR includes a minor refactoring of the building of the JSON response in case of an internal `HTTPException`. The changes uses Pydantic's `BaseModel`'s interface for JSON serialization instead. This make the involved code more direct and consistent with rest of the project.
> Use Pydantic's `BaseModel`'s interface for JSON serialization instead in building of the JSON error responses

- .github/workflows/test.yml
- setup.cfg
This PR does two things:
1. Fix the Python env to specs in `requirements.txt`. This will allow finer control in the versions of dependent packages got installed in the workflow environment.
2. Restrict Flask to version below 3.0. The latest version of Flask, 3.0, doesn't work with the existing code. Let's restrict the version of Flask to be below 3.0 for now and update the code base to support Flask 3.0+ in another occasion.
> Fix the Python env to specs in `requirements.txt` and restrict Flask version

- datalad_registry/tasks/__init__.py
It is now known that `datalad.api.meta_extract()`, defaulting the `return_type` param, returns a list of exactly one element for certain. This PR make the `extract_ds_meta` Celery task adapt to this behavior of `datalad.api.meta_extract()`.
This PR is based on #238. To get the relevant commits of this PR, the associated branch should be merge with master after #238 is merged into master.
> Adjust to `datalad.api.meta_extract()` returning one element

- datalad_registry/tests/conftest.py
This PR ensures that the flask app fixture used in tests provides a clean instance folder for the Flask app initially.
> Clear instance path in flask app fixture

- datalad_registry/tasks/__init__.py
- datalad_registry/tasks/utils/__init__.py
Simplify the helper `validate_url_is_processed()`. It is really better to just check the `processed` without checking the `cache_path` of the URL in the sense that a processed URL always have a cache path and mypy required cache path to be assert to be not None in context.
This PR is based on #262. To get the relevant commits related with this PR, the master branch should be merged into the associated branch of this PR after #262  is merged into the master branch.
> Simplify `validate_url_is_processed`

- docker-compose.dev.yml
This PR removes the worker service dependency from the scheduler and monitor services. The startups and shutdowns of the scheduler and monitor services don't really depend on the worker service.
> Remove worker service dependency in Docker Compose file

- tools/populate_datasets.datalad.org
This PR eliminate the shellcheck complain about calling `read` without the `-r` option.
We should be able to call `read` with the `-r` option in the use case since URLs can't contain `"\"`.
> Eliminate shellcheck err in by adding `-r` option

- datalad_registry/templates/overview.html
- docker-compose.dev.local.override.yml
Makes it easy to navigate the "forks" of a given dataset -- pretty neat.
1st commit is needed to get it working locally, a version of it is also in #278
> make ds id column value into a hyperlink to search for that uuid

- dev.Dockerfile
Including the python3-gdbm package significantly improves the performance of the monitor, Flower, service, particularly in DB queries.
> Include the python3-gdbm package in Docker image

- dev.Dockerfile
- docker-compose.dev.local.override.yml
- docker-compose.dev.yml
- docker-compose.read-only.local.override.yml
This PR contains the following improvements in container services specification.
1. Container services are now utilizing the init process provided by https://github.com/phusion/baseimage-docker to ensure all orphaned processes are reaped. Thus, this PR closes https://github.com/datalad/datalad-registry/issues/283.
2. Elimination of the calls to `bash` in invoking the command to be executed for a container when the calls can be avoided.
3. The use of `exec` to ensure a `SIGTERM` signal is received by the target process of a container when `docker/podman stop` are used.
4. Upgrading the operating system inside the container when building the container images. This improve the security of the container. See https://github.com/phusion/baseimage-docker?tab=readme-ov-file#upgrading-the-operating …
> Ensuring container services having the correct init process and other improvements related to container services

- datalad_registry/conf.py
- datalad_registry/tests/test_conf.py
Rename `operation_mode_to_config_cls` to `OPERATION_MODE_TO_CONFIG_CLS` in conf.py. It is more appropriate for the map/dict to be named so since it is a constant.
> Rename `operation_mode_to_config_cls` to `OPERATION_MODE_TO_CONFIG_CLS` in conf.py

- datalad_registry/tests/test_conf.py
The only environment var needed to be set is `DATALAD_REGISTRY_OPERATION_MODE` in this test.
> Eliminate unneeded code to set up the environment variables in `TestCompileConfigFromEnv.test_invalid_op_mode()`

- datalad_registry/blueprints/api/__init__.py
- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/url_metadata/__init__.py
- datalad_registry/conf.py
- datalad_registry/tasks/__init__.py
- datalad_registry/tasks/utils/usage_dashboard.py
- datalad_registry/tests/test__init__.py
- datalad_registry/tests/test_conf.py
- datalad_registry/tests/test_tasks/test_usage_dashboard_sync.py
- datalad_registry_client/submit_urls.py
- docker-compose.dev.yml
- requirements_dev.txt
- setup.cfg
- tools/populate.py
- tools/sync_with_user_dashboard.py
This PR does the following.
1. Implements a periodic Celery task for ensuring all active repos presented in [datalad-usage-dashboard](https://github.com/datalad/datalad-usage-dashboard) are registered in Datalad-Registry (excepts repos from OSF which will be supported later). This PR closes #271.
2. Provides a script to invoke the above Celery task on demand. Thus, an empty instance of Datalad-Registry can be populated with all the active repos presented in the usage dashboard by running this script. 
3. Refactor some of the Pydantic models used by `tools.populate.py` so that these models can be used by the aforementioned Celery task as well.
4. [`responses`](https://github.com/getsentry/responses) will be added as a dependency for testing for the purpose of mocking out the `requests` …
> Sync Datalad-Registry with datalad-usage-dashboard

- requirements.txt
This version corrects the issue we had with `0.4.18`. https://github.com/datalad/datalad-metalad/issues/403
> Upgrade `datalad-metalad` dependency

- datalad_registry/blueprints/api/dataset_urls/models.py
- requirements.txt
This PR ensures that the JSON schema for a Pydantic model used in a web API response are constructed using the names, instead of the aliases, of the fields in the model.
This PR closes #191.
> Use Field names instead of aliases in constructing JSON schema for response Pydantic model(s)

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
This PR renames some fields in the models used in web API responses so that the names are consistent with the models used for accessing the database. In this process, the alias of these renamed fields are eliminated because they are no longer necessary.
> Remove needed use of aliases in Pydantic models

- .github/workflows/test.yml
It is needed for v4 -- we added that secret at the level of the organization so should be available
> Do provide secret token for CODECOV

- dev.Dockerfile
Datalad is already installed through pip, so the installation through apt-get is unneeded and shouldn't be included in the container image.
> Remove Datalad installation through apt-get in container image

- datalad_registry/static/main.css
This PR configure the web UI so that the 'Nr of Annexed files' and 'Size of Annexed files' headers occupy different columns. 
This closes #302 which is due to table cells not being able to align to table headers.
> Configure the web UI so that the 'Nr of Annexed files' and 'Size of Annexed files' headers occupy different columns

- docker-compose.dev.yml
This PR increases the time interval between savings of Flower's state. Each saving of Flower's state causes a complete re-write of the [DB](https://flower.readthedocs.io/en/latest/config.html#db) for storing Flower's state, so this interval must be sufficiently large to avoid overworking the CPU and the storage hardware.
This PR closes #258 and #301.
Note: Once this PR is merged. We need to switch the directory containing the DB file, `flower`, back to a spindle hard drive.
> Increase the interval between savings of `Flower`'s state

- docker-compose.read-only.yml
- docker-compose.testing.yml
- docker-compose.yml
This PR pins the version of Postgres to be used to version 15.
To sync the primary and read-only instances of Datalad-Registry, their Postgres DB services have to be in the same version. Pinning the Docker image of Postgres to be used in different Docker Compose files will help ensure that the same version of Postgres to be used across different instances of Datalad-Registry. Since our current live instances of Datalad-Registry have Postgres at version 15, version 15 is picked.
Note: To get the relevant commits of this PR, merge the master branch to this branch after #306 is merged to the master.
> Pin Postgres version

- datalad_registry/search.py
This PR addresses the issue describe in https://github.com/datalad/datalad-registry/pull/308#issuecomment-1961967932. The changes in this PR passes the tests describe in the issue. However, it causes some failures in other tests. I am unable to resolve the new failures at this point because they seems to be related to lark.
The rationale behind this fix as explained by ChatGPT.
> 
> You're correct in pointing out a misconception in my previous explanation regarding the evaluation of conditions involving `NULL` values in SQL. Let's clarify the behavior, especially in the context of your question about the behavior of `NULL` with `ILIKE` and logical operators.
> 
> In SQL, when you evaluate an expression involving `NULL` with a comparison operator (such as `=`, `!=`, `<`, `>`, `LIKE`, …
> Handle `NULL` column values correctly in `ilike` queries

- datalad_registry/tests/test_overview.py
- datalad_registry/tests/test_search.py
This PR re-organized some tests introduced (or modified) in #308, so that their intend is more clear.
> Modify tests organization

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
This PR corrects the generation of the link of the last page in a paginated result. Specifically, when a paginated result contains no item, i.e. having 0 page in return, the correct last page should be 1 instead of 0.
Additionally, a related test is also updated in this PR to verify the related behavior.
> Fix the link for the last page of pagination in API

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
This PR exposes the search functionality available in the web UI through the API. It closes #269.
The search functionality is exposed via the query parameter `search` to the existing collection endpoint of `/api/v2/dataset-urls`. This parameter can be mix with other parameters at that endpoint to create more restricted searchs.
Note: The changes in this PR has been applied to the live instances of DL-Registry.
> Expose search functionality in API

- docker-compose.dev.override.yml
This PR prevents a Datalad-Registry instance used for development to sync automatically with [datalad-usage-dashboard](https://github.com/datalad/datalad-usage-dashboard).
> Prevent automatic syncing with datalad-usage-dashboard

- pyproject.toml
Upgrade to the latest compatible versions starting at 3.0.0
> Upgrade `versioningit` dependency used by the build system

- datalad_registry/__init__.py
- datalad_registry_client/__init__.py
The supported version of Python in this project is >= `3.9`, so `importlib.metadata` is available through stdlib
> Remove the use of `importlib_metadata`

- README.md
This PR adds the prerequisite of requiring tags from the [the Datalad-Registry repository](https://github.com/datalad/datalad-registry) to build the DL-Registry package to `README.md`. It closes https://github.com/datalad/datalad-registry/issues/334.
> Add tag prerequisite for building DL-Registry package

- README.md
Per https://github.com/datalad/datalad-registry/pull/337#discussion_r1532115613, the description of the prerequisite for tags is indeed too verbose in `README.md`. This PR revises the description to reduce verbosity.
> Make prerequisite for tags less verbose in `README.md`

- datalad_registry/search.py
- datalad_registry/tests/test_search.py
This PR restricts inputs to `search.parse_query` to non-empty strings. An empty query string as an input to the parser will result in `lark.exceptions.UnexpectedEOF` anyway. It is more explicit and informative to rule out this input in the `parse_query` function level.
> Restrict inputs to `search.parse_query` to non-empty strings

- datalad_registry/search.py
- datalad_registry/tests/test_search.py
This PR restricts inputs to `search.parse_query` to strings that doesn't contain only whitespace characters. An string containing only whitespace as an input to the parser will result in lark.exceptions.UnexpectedEOF anyway. It is more explicit and informative to rule out this input in the parse_query function level.
This PR is similar to #344.
> Limit arg in `search.parse_query` to non-white space only str

- datalad_registry/overview.py
- datalad_registry/templates/overview.html
- datalad_registry/tests/test_overview.py
The main purpose of this PR is to remove the conflation of the case in which the search query string is not provided and the case in which the search query string is an empty string. Removing this conflation will help to develop will permit better consistency and flexibility and make the intent more clear across the app.
Per ChatGPT:
> The pattern `if query:` in the context of checking if a request parameter (`query` in this case) is provided and non-empty is common in web development. This approach effectively treats a missing parameter (`None`) and an empty string (`""`) the same way, which simplifies handling request parameters that are expected to be non-empty strings when provided.
> 
> This practice can be considered good or bad depending on the specific requirements of your …
> Handle empty search query string in web UI

- datalad_registry/tasks/__init__.py
The change in this PR will ensure the requirement of datalad-id of the `metalad_core` extractor is met in terms of required file.
The failures depicted below in running the `metalad_core` extractor be eliminated because of this change.
> Add ".datalad/config" to be a required file for `metalad_core`

- migrations/env.py
We currently support `Flask-SQLAlchemy` and beyond, so `db.get_engine` is deprecated and no longer needed.
This change will remove the following deprecation warning when running migration related tasks.
```sh
/app/migrations/env.py:20: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
return current_app.extensions["migrate"].db.get_engine()
```
> Remove use of `db.get_engine` in db migration code

- datalad_registry/tests/test_utils/test_datalad_tls.py
- datalad_registry/utils/datalad_tls.py
- migrations/versions/7d283978c4a9_change_repourl_branches_to_a_dict.py
This PR modifies how `branches` are stored in the DB, from a list of dictionary to a dictionary with branch names are keys.
This PR also includes the needed migration script.
Note: Changes in this PR has been applied to the live instances of DL-Registry.
> Modify how `branches` are stored in the DB

- datalad_registry/blueprints/api/dataset_urls/__init__.py
- datalad_registry/blueprints/api/dataset_urls/models.py
- datalad_registry/blueprints/api/dataset_urls/tools.py
- datalad_registry/blueprints/api/utils.py
- datalad_registry/overview.py
- datalad_registry/static/main.css
- datalad_registry/templates/overview.html
- datalad_registry/tests/conftest.py
- datalad_registry/tests/test_blueprints/test_api/test_dataset_urls.py
- datalad_registry/tests/test_overview.py
- datalad_registry/tests/test_search.py
- datalad_registry/tests/test_tasks/test_chk_url_to_update.py
- datalad_registry/tests/test_tasks/test_mark_for_chk.py
- datalad_registry/tests/tools.py
- datalad_registry_client/tests/test_get_urls.py
This PR provides stats regarding the returned collection of a query of dataset URLs. It closes #349.
Stats on unique datasets are only calculated on Datalad datasets. We can extend the changes in this PR to provide stats on guessed unique non-Datalad datasets in the future harvesting more info from the repos and choosing the logic that does the guessing work.
Note: 
- The changes in this PR has been applied to the instance on Typhon but not yet Falkor.
- With stats gathered, the search function is palpably slower.
> Provide stats about return collection

- datalad_registry/blueprints/api/url_metadata/models.py
- datalad_registry/tests/test_blueprints/test_api/test_url_metadata.py
This PR allows extracted metadata to be any type in the API response.
This change is needed because extracted metadata can be any type. The `dandi:files` extractor can return extracted metadata as a list for example.
Note: Related tests are update to better tests cases in which extracted metadata is not a `dict`.
> BF: allows extracted metadata to be any type

- .github/workflows/test.yml
This eliminates a warning from the IDE.
> Use https instead of http in neuro debian

- .github/workflows/test.yml
Set up tmate debugging for the Tests GitHub Action workflow to be triggered manually
> Set up Tests GitHub Action workflow with tmate debugging

- .github/workflows/shellcheck.yml
- .github/workflows/test.yml
- .github/workflows/type_check.yml
This PR refactor GitHub Actions workflows in the following manner.
1. Rename some of the jobs to avoid confusion
2. Remove static type checking from the `test.yml` workflow to put it in a specific workflow
> Refactor GitHub Actions workflows
